version: "3"
services: 
  grafana:
    image: grafana/grafana:7.1.3
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-storage:/var/lib/grafana
    ports: 
      - "3000:3000"
    environment: 
      - "GF_PLUGINS_ENABLE_ALPHA=true"
      # Only need this on first start???
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel"