version: "3.7"
services: 
  cla-assistant:
    image: mojaloop/cla-assistant:local
    build: 
      context: ./cla-assistant
    ports: 
      - "5000:5000"
    environment: 
      - HOST=706a76112e4e.ngrok.io
      - PROTOCOL=https
      - MONGODB=mongodb://cla-user:cla-pass@mongo:27017/cla-db
    env_file: 
      - ./docker/.env

  mongo:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:password
      - MONGO_INITDB_DATABASE=cla-db
    volumes:
      - ./docker/mongodb/db:/data/db
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
